config/routes.rb
Rails.application.routes.draw do
  resources :personagems
  resources :users
  resources :chars
  resources :sessions, only: [:new, :create, :destroy]
  root  'welcome#home'

  get "home/logout"
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'welcome#help',    via: 'get'
  match '/welcome/about',   to: 'welcome#about',   via: 'get'
  match '/about', to: 'welcome#about', via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/rpg',     to: 'rpg#index', via: 'get'
  match '/rpg/index', to: 'rpg#show', via: 'get'
  match '/rpg/loja',    to: 'rpg#loja', via: 'get'
  match '/rpg/loja/damage', to: 'item#comprardano', via: 'get'
  match '/rpg/atacar', to: 'rpg#targets', via: 'get'
  match '/index', to: 'welcome#index', via: 'get'
  match '/personagems/teste', to: 'personagem#show', via: 'get'
  match '/rpg/targets', to: 'rpg#targets', via: 'get'
  match '/rpg/cidade', to: 'rpg#cidade', via: 'get'

end

app/controllers/chars_controller.rb
class CharsController < ApplicationController
  before_action :set_char, only: [:show, :edit, :update, :destroy]

  # GET /chars
  # GET /chars.json
  def index
    @chars = Char.all
  end

  # GET /chars/1
  # GET /chars/1.json
  def show
  end

  # GET /chars/new
  def new
    @char = Char.new
  end

  # GET /chars/1/edit
  def edit
  end

  # POST /chars
  # POST /chars.json
  def create
    @char = Char.new(char_params)

    respond_to do |format|
      if @char.save
        format.html { redirect_to @char, notice: 'Char was successfully created.' }
        format.json { render :show, status: :created, location: @char }
      else
        format.html { render :new }
        format.json { render json: @char.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chars/1
  # PATCH/PUT /chars/1.json
  def update
    respond_to do |format|
      if @char.update(char_params)
        format.html { redirect_to @char, notice: 'Char was successfully updated.' }
        format.json { render :show, status: :ok, location: @char }
      else
        format.html { render :edit }
        format.json { render json: @char.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chars/1
  # DELETE /chars/1.json
  def destroy
    @char.destroy
    respond_to do |format|
      format.html { redirect_to chars_url, notice: 'Char was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_char
      @char = Char.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def char_params
      params.require(:char).permit(:hpmax, :umid, :teste)
    end
end

app/helpers/chars_helper.rb
module CharsHelper
end

app/views/chars/_form.html.erb
<%= form_for(@char) do |f| %>
  <% if @char.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@char.errors.count, "error") %> prohibited this char from being saved:</h2>

      <ul>
      <% @char.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hpmax %><br>
    <%= f.number_field :hpmax %>
  </div>
  <div class="field">
    <%= f.label :umid %><br>
    <%= f.number_field :umid %>
  </div>
  <div class="field">
    <%= f.label :teste %><br>
  <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chars/edit.html.erb
<h1>Editing char</h1>

<%= render 'form' %>

<%= link_to 'Show', @char %> |
<%= link_to 'Back', chars_path %>

app/views/chars/index.html.erb
<h1>Listing chars</h1>

<table>
  <thead>
    <tr>
      <th>Hpmax</th>
      <th>Umid</th>
      <th>Teste</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chars.each do |char| %>
      <tr>
        <td><%= char.hpmax %></td>
        <td><%= char.umid %></td>
        <td><%= char.teste %></td>
        <td><%= link_to 'Show', char %></td>
        <td><%= link_to 'Edit', edit_char_path(char) %></td>
        <td><%= link_to 'Destroy', char, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Char', new_char_path %>

app/views/chars/new.html.erb
<h1>New char</h1>

<%= render 'form' %>

<%= link_to 'Back', chars_path %>

app/views/chars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hpmax:</strong>
  <%= @char.hpmax %>
</p>

<p>
  <strong>Umid:</strong>
  <%= @char.umid %>
</p>

<p>
  <strong>Teste:</strong>
  <%= @char.teste %>
</p>

<%= link_to 'Edit', edit_char_path(@char) %> |
<%= link_to 'Back', chars_path %>