config/routes.rb
Rails.application.routes.draw do
  resources :personagems
  resources :users
  resources :chars
  resources :sessions, only: [:new, :create, :destroy]
  root  'welcome#home'

  get "home/logout"
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'welcome#help',    via: 'get'
  match '/welcome/about',   to: 'welcome#about',   via: 'get'
  match '/about', to: 'welcome#about', via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/rpg',     to: 'rpg#index', via: 'get'
  match '/rpg/index', to: 'rpg#show', via: 'get'
  match '/rpg/loja',    to: 'rpg#loja', via: 'get'
  match '/rpg/loja/damage', to: 'item#comprardano', via: 'get'
  match '/rpg/atacar', to: 'rpg#targets', via: 'get'
  match '/index', to: 'welcome#index', via: 'get'
  match '/personagems/teste', to: 'personagem#show', via: 'get'
  match '/rpg/targets', to: 'rpg#targets', via: 'get'
  match '/rpg/cidade', to: 'rpg#cidade', via: 'get'

end

app/models/personagem.rb
class Personagem < ActiveRecord::Base

	belongs_to :user

	after_initialize :default_values
	def default_values
  		self.damage = 15
  		self.hpMax = 50
  		self.hpActual = 50
  		self.defense = 0
  		self.atacable = true
  		self.exp = 0
  		self.cidade = false
  		self.gold = 100
  		self.deaths = 0
  		self.kills = 0
	end


end

app/controllers/personagems_controller.rb
class PersonagemsController < ApplicationController
  before_action :set_personagem, only: [:show, :edit, :update, :destroy]

  # GET /personagems
  # GET /personagems.json
  def index
    @personagems = Personagem.all
  end

  # GET /personagems/1
  # GET /personagems/1.json
  def show
    @personagems = Personagem.where(atacable: true)
  end

  # GET /personagems/new
  def new
    @personagem = Personagem.new
  end

  # GET /personagems/1/edit
  def edit
  end

  # POST /personagems
  # POST /personagems.json
  def create
    @personagem = Personagem.new(personagem_params)

    respond_to do |format|
      if @personagem.save
        format.html { redirect_to @personagem, notice: 'Personagem was successfully created.' }
        format.json { render :show, status: :created, location: @personagem }
      else
        format.html { render :new }
        format.json { render json: @personagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personagems/1
  # PATCH/PUT /personagems/1.json
  def update
    respond_to do |format|
      if @personagem.update(personagem_params)
        format.html { redirect_to @personagem, notice: 'Personagem was successfully updated.' }
        format.json { render :show, status: :ok, location: @personagem }
      else
        format.html { render :edit }
        format.json { render json: @personagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personagems/1
  # DELETE /personagems/1.json
  def destroy
    @personagem.destroy
    respond_to do |format|
      format.html { redirect_to personagems_url, notice: 'Personagem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personagem
      @personagem = Personagem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personagem_params
      params.require(:personagem).permit(:damage, :exp, :hpMax, :hpActual, :defense)
    end
end

app/helpers/personagems_helper.rb
module PersonagemsHelper
end

app/views/personagems/_form.html.erb
<%= form_for(@personagem) do |f| %>
  <% if @personagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personagem.errors.count, "error") %> prohibited this personagem from being saved:</h2>

      <ul>
      <% @personagem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :damage %><br>
    <%= f.text_field :damage %>
  </div>
  <div class="field">
    <%= f.label :exp %><br>
    <%= f.number_field :exp %>
  </div>
  <div class="field">
    <%= f.label :hpMax %><br>
    <%= f.text_field :hpMax %>
  </div>
  <div class="field">
    <%= f.label :hpActual %><br>
    <%= f.text_field :hpActual %>
  </div>
  <div class="field">
    <%= f.label :defense %><br>
    <%= f.text_field :defense %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personagems/edit.html.erb
<h1>Editing personagem</h1>

<%= render 'form' %>

<%= link_to 'Show', @personagem %> |
<%= link_to 'Back', personagems_path %>

app/views/personagems/index.html.erb
<h1>Listing personagems</h1>

<table>
  <thead>
    <tr>
      <th>Damage</th>
      <th>Exp</th>
      <th>Hpmax</th>
      <th>Hpactual</th>
      <th>Defense</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personagems.each do |personagem| %>
      <tr>
        <td><%= personagem.damage %></td>
        <td><%= personagem.exp %></td>
        <td><%= personagem.hpMax %></td>
        <td><%= personagem.hpActual %></td>
        <td><%= personagem.defense %></td>
        <td><%= link_to 'Show', personagem %></td>
        <td><%= link_to 'Edit', edit_personagem_path(personagem) %></td>
        <td><%= link_to 'Destroy', personagem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personagem', new_personagem_path %>

app/views/personagems/index2.html.erb
<h1>Listing personagems</h1>

<table>
  <thead>
    <tr>
      <th>Damage</th>
      <th>Exp</th>
      <th>Hpmax</th>
      <th>Hpactual</th>
      <th>Defense</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personagems.each do |personagem| %>
      <tr>
        <td><%= personagem.damage %></td>
        <td><%= personagem.exp %></td>
        <td><%= personagem.hpMax %></td>
        <td><%= personagem.hpActual %></td>
        <td><%= personagem.defense %></td>
        <td><%= link_to 'Show', personagem %></td>
        <td><%= link_to 'Edit', edit_personagem_path(personagem) %></td>
        <td><%= link_to 'Destroy', personagem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personagem', new_personagem_path %>

app/views/personagems/new.html.erb
<h1>New personagem</h1>

<%= render 'form' %>

<%= link_to 'Back', personagems_path %>

app/views/personagems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Damage:</strong>
  <%= @personagem.damage %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @personagem.exp %>
</p>

<p>
  <strong>Hpmax:</strong>
  <%= @personagem.hpMax %>
</p>

<p>
  <strong>Hpactual:</strong>
  <%= @personagem.hpActual %>
</p>

<p>
  <strong>Defense:</strong>
  <%= @personagem.defense %>
</p>

<%= link_to 'Edit', edit_personagem_path(@personagem) %> |
<%= link_to 'Back', personagems_path %>